version: "3.2"
services:
  ponto_api:
    depends_on:
        - mysql_db
    image: node:slim
    container_name: ponto_api
    restart: always
    env_file: 
      - .env.docker
    ports: 
      - 8088:8088
    volumes: 
      - .:/usr/app/
    working_dir: /usr/app/
    command: "npx tsx watch src/index.ts"
    logging: 
      driver: "json-file"
      options: 
        max-size: "10m"
        max-file: "5"
  mysql_db:
    image: mysql:latest
    container_name: ponto_mysql
    restart: always
    env_file: 
      - .env.docker
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./emponto_dump.sql:/docker-entrypoint-initdb.d/emponto_dump.sql
volumes:
  mysql_data:                   